channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - xarray
  - matplotlib
  - cartopy
  - cdflib
  - pip
  - pip:
      - treebeard
      - watermark
      - viresclient
      - python-dotenv