name: swarmpal-runner
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - watermark
  # swarmpal dependencies
  - cartopy
  - dask
  - matplotlib
  - numpy
  - pandas
  - pyproj
  - scipy
  - xarray
  - xarray-datatree
  - hapiclient
  - viresclient
