# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Swarm Quicklooks
author: "Ashley Smith et al."
logo: ""
only_build_toc_files: true

execute:
  execute_notebooks: "off"

launch_buttons:
  notebook_interface        : jupyterlab
  jupyterhub_url            : "https://vre.vires.services"
  binderhub_url             : ""

repository:
  url: https://github.com/Swarm-DISC/Swarm_quicklooks
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button      : false
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
  home_page_in_navbar       : true
  comments:
    hypothesis              : false

# See https://jupyterbook.org/content/content-blocks.html
parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - deflist
